### ISSUE TITLE
通过这个项目找到了web 推RTMP流的思路。十分感谢

### ISSUE THREAD

**Issue by myfmyy** [JackyM06/WebPushMedia#13]
开始完全照着这个项目吵了一遍，发现了几个问题。
    1、即使是用本地RTMP服务器测试延迟也高达17秒左右（flv）
    2、msr经常遇到ondataavailable无回调的情况（例如stream里没有AudioTrack，或者获取间隔低于1s），并且msr项目已经停止维护了

我的解决方法是选择直接用浏览器的MediaRecorder，也不用node-fluent-ffmpeg把blob存ts再推，而是直接用nodejs子进程命令行调ffmpeg再把blob写入（.stdin.write(blob)）。最后本地RTMP服务器延迟只有2～3秒(flv)

最后还是感谢这个项目提供的代码和思路！

**Comment by JackyM06** [comment]
很酷的优化思路，感谢你的建议～
